### ISSUE TITLE
Keeps erroring when i try to build

### ISSUE THREAD

**Issue by Arth795-scripts** [dehoisted/Cleo#4]
Build started...
1>------ Build started: Project: Cleo, Configuration: Release x64 ------
1>Anti.cpp
1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(17,56): error C2429: language feature 'init-statements in if/switch' requires compiler flag '/std:c++17'
1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(24,1): error C2511: 'void Anti::check_usernames(void) const': overloaded member function not found in 'Anti'
1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.h(12): message : see declaration of 'Anti'
1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(33,48): error C2429: language feature 'init-statements in if/switch' requires compiler flag '/std:c++17'
1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(36,49): error C2429: language feature 'init-statements in if/switch' requires compiler flag '/std:c++17'
1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(39,49): error C2429: language feature 'init-statements in if/switch' requires compiler flag '/std:c++17'
1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(42,50): error C2429: language feature 'init-statements in if/switch' requires compiler flag '/std:c++17'
1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(45,50): error C2429: language feature 'init-statements in if/switch' requires compiler flag '/std:c++17'
1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(48,49): error C2429: language feature 'init-statements in if/switch' requires compiler flag '/std:c++17'
1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(51,54): error C2429: language feature 'init-statements in if/switch' requires compiler flag '/std:c++17'
1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(54,47): error C2429: language feature 'init-statements in if/switch' requires compiler flag '/std:c++17'
1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(57,49): error C2429: language feature 'init-statements in if/switch' requires compiler flag '/std:c++17'
1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(60,54): error C2429: language feature 'init-statements in if/switch' requires compiler flag '/std:c++17'
1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(65,1): error C2511: 'HANDLE Anti::find_process(const char *)': overloaded member function not found in 'Anti'
1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.h(12): message : see declaration of 'Anti'
1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(72,6): error C2664: 'int strcmp(const char *,const char *)': cannot convert argument 1 from 'WCHAR [260]' to 'const char *'
1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(72,20): message : Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\ucrt\string.h(100,13): message : see declaration of 'strcmp'
1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(74,87): error C2429: language feature 'init-statements in if/switch' requires compiler flag '/std:c++17'
1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(91,5): error C2664: 'LSTATUS RegOpenKeyExW(HKEY,LPCWSTR,DWORD,REGSAM,PHKEY)': cannot convert argument 2 from 'ay::obfuscated_data<26,6531858508656880489>' to 'LPCWSTR'
1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(91,39): message : No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winreg.h(781,1): message : see declaration of 'RegOpenKeyExW'
1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(95,5): error C2664: 'LSTATUS RegOpenKeyExW(HKEY,LPCWSTR,DWORD,REGSAM,PHKEY)': cannot convert argument 2 from 'ay::obfuscated_data<52,6531858508656880489>' to 'LPCWSTR'
1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(95,39): message : No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winreg.h(781,1): message : see declaration of 'RegOpenKeyExW'
1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(100,5): error C2664: 'LSTATUS RegOpenKeyExW(HKEY,LPCWSTR,DWORD,REGSAM,PHKEY)': cannot convert argument 2 from 'ay::obfuscated_data<14,6531858508656880489>' to 'LPCWSTR'
1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(100,39): message : No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winreg.h(781,1): message : see declaration of 'RegOpenKeyExW'
1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(108,39): error C2429: language feature 'init-statements in if/switch' requires compiler flag '/std:c++17'
1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(122,31): error C2429: language feature 'init-statements in if/switch' requires compiler flag '/std:c++17'
1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(169,77): error C2429: language feature 'init-statements in if/switch' requires compiler flag '/std:c++17'
1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(173,46): error C3861: '__readfsdword': identifier not found
1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(174,14): error C2737: '_peb32': const object must be initialized
1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(175,63): warning C4312: 'reinterpret_cast': conversion from 'DWORD' to 'PDWORD' of greater size
1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(178,42): error C3861: '__readfsdword': identifier not found
1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(184,87): error C2429: language feature 'init-statements in if/switch' requires compiler flag '/std:c++17'
1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(190,58): error C2664: 'HMODULE GetModuleHandleW(LPCWSTR)': cannot convert argument 1 from 'const char [13]' to 'LPCWSTR'
1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(190,44): message : Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\libloaderapi.h(269,1): message : see declaration of 'GetModuleHandleW'
1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(190,16): error C2737: 'hKernel32': const object must be initialized
1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(218,8): error C2664: 'int strcmp(const char *,const char *)': cannot convert argument 1 from 'WCHAR [260]' to 'const char *'
1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(218,22): message : Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\ucrt\string.h(100,13): message : see declaration of 'strcmp'
1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(220,89): error C2429: language feature 'init-statements in if/switch' requires compiler flag '/std:c++17'
1>Main.cpp
1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Modules.h(3,10): fatal error C1083: Cannot open include file: 'cpr/cpr.h': No such file or directory
1>User.cpp
1>The contents of <filesystem> are available only with C++17 or later.
1>C:\Users\mbell\Desktop\Cleo-main\Cleo\User.h(5,10): fatal error C1083: Cannot open include file: 'cpr/cpr.h': No such file or directory
1>Done building project "Cleo.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

please help

**Comment by dehoisted** [comment]
> Build started... 1>------ Build started: Project: Cleo, Configuration: Release x64 ------ 1>Anti.cpp 1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(17,56): error C2429: language feature 'init-statements in if/switch' requires compiler flag '/std:c++17' 1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(24,1): error C2511: 'void Anti::check_usernames(void) const': overloaded member function not found in 'Anti' 1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.h(12): message : see declaration of 'Anti' 1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(33,48): error C2429: language feature 'init-statements in if/switch' requires compiler flag '/std:c++17' 1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(36,49): error C2429: language feature 'init-statements in if/switch' requires compiler flag '/std:c++17' 1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(39,49): error C2429: language feature 'init-statements in if/switch' requires compiler flag '/std:c++17' 1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(42,50): error C2429: language feature 'init-statements in if/switch' requires compiler flag '/std:c++17' 1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(45,50): error C2429: language feature 'init-statements in if/switch' requires compiler flag '/std:c++17' 1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(48,49): error C2429: language feature 'init-statements in if/switch' requires compiler flag '/std:c++17' 1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(51,54): error C2429: language feature 'init-statements in if/switch' requires compiler flag '/std:c++17' 1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(54,47): error C2429: language feature 'init-statements in if/switch' requires compiler flag '/std:c++17' 1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(57,49): error C2429: language feature 'init-statements in if/switch' requires compiler flag '/std:c++17' 1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(60,54): error C2429: language feature 'init-statements in if/switch' requires compiler flag '/std:c++17' 1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(65,1): error C2511: 'HANDLE Anti::find_process(const char *)': overloaded member function not found in 'Anti' 1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.h(12): message : see declaration of 'Anti' 1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(72,6): error C2664: 'int strcmp(const char *,const char *)': cannot convert argument 1 from 'WCHAR [260]' to 'const char *' 1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(72,20): message : Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast 1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\ucrt\string.h(100,13): message : see declaration of 'strcmp' 1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(74,87): error C2429: language feature 'init-statements in if/switch' requires compiler flag '/std:c++17' 1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(91,5): error C2664: 'LSTATUS RegOpenKeyExW(HKEY,LPCWSTR,DWORD,REGSAM,PHKEY)': cannot convert argument 2 from 'ay::obfuscated_data<26,6531858508656880489>' to 'LPCWSTR' 1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(91,39): message : No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called 1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winreg.h(781,1): message : see declaration of 'RegOpenKeyExW' 1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(95,5): error C2664: 'LSTATUS RegOpenKeyExW(HKEY,LPCWSTR,DWORD,REGSAM,PHKEY)': cannot convert argument 2 from 'ay::obfuscated_data<52,6531858508656880489>' to 'LPCWSTR' 1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(95,39): message : No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called 1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winreg.h(781,1): message : see declaration of 'RegOpenKeyExW' 1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(100,5): error C2664: 'LSTATUS RegOpenKeyExW(HKEY,LPCWSTR,DWORD,REGSAM,PHKEY)': cannot convert argument 2 from 'ay::obfuscated_data<14,6531858508656880489>' to 'LPCWSTR' 1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(100,39): message : No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called 1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winreg.h(781,1): message : see declaration of 'RegOpenKeyExW' 1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(108,39): error C2429: language feature 'init-statements in if/switch' requires compiler flag '/std:c++17' 1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(122,31): error C2429: language feature 'init-statements in if/switch' requires compiler flag '/std:c++17' 1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(169,77): error C2429: language feature 'init-statements in if/switch' requires compiler flag '/std:c++17' 1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(173,46): error C3861: '__readfsdword': identifier not found 1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(174,14): error C2737: '_peb32': const object must be initialized 1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(175,63): warning C4312: 'reinterpret_cast': conversion from 'DWORD' to 'PDWORD' of greater size 1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(178,42): error C3861: '__readfsdword': identifier not found 1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(184,87): error C2429: language feature 'init-statements in if/switch' requires compiler flag '/std:c++17' 1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(190,58): error C2664: 'HMODULE GetModuleHandleW(LPCWSTR)': cannot convert argument 1 from 'const char [13]' to 'LPCWSTR' 1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(190,44): message : Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast 1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\libloaderapi.h(269,1): message : see declaration of 'GetModuleHandleW' 1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(190,16): error C2737: 'hKernel32': const object must be initialized 1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(218,8): error C2664: 'int strcmp(const char *,const char *)': cannot convert argument 1 from 'WCHAR [260]' to 'const char *' 1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(218,22): message : Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast 1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\ucrt\string.h(100,13): message : see declaration of 'strcmp' 1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Anti.cpp(220,89): error C2429: language feature 'init-statements in if/switch' requires compiler flag '/std:c++17' 1>Main.cpp 1>C:\Users\mbell\Desktop\Cleo-main\Cleo\Modules.h(3,10): fatal error C1083: Cannot open include file: 'cpr/cpr.h': No such file or directory 1>User.cpp 1>The contents of are available only with C++17 or later. 1>C:\Users\mbell\Desktop\Cleo-main\Cleo\User.h(5,10): fatal error C1083: Cannot open include file: 'cpr/cpr.h': No such file or directory 1>Done building project "Cleo.vcxproj" -- FAILED. ========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
> 
> please help

You’re not on C++ 17; go to your project settings to change your version of C++.
