### ISSUE TITLE
Unable to understand install process.

### ISSUE THREAD

**Issue by ghost** [dehoisted/Cleo#5]
I am trying to install Cleo to test the capabilities of my Anti Virus software against discord malware. 

I am running into an error when getting the dependencies using the ps1 file.
![image](https://user-images.githubusercontent.com/85327029/158398792-a20f641b-c1aa-4cf1-94f0-de3ed2693123.png)
I have an install of visual studio but cannot see why it is failing
![image](https://user-images.githubusercontent.com/85327029/158398889-1b9fd7ef-11dd-4793-9b41-03bc00ef6336.png)

Secondly even if i could get through this road block i do not understand what to do from here. Any video tutorials or even tutorials that can easily simplify how to install Cleo would help me tons. Thank you for reading.

**Comment by Passive** [comment]
You should be using the repository on my profile instead, this is outdated and bad
